### PR TITLE
test

### PR DESCRIPTION
**Pull request by isacikgoz**

### CODE REVIEW

**Comment by agnivade** [comment]
commenting!

**Comment by agnivade** [comment]
normal comment!

**Comment by isacikgoz** [comment]
In response to [this](https://github.com/mattermosttest/mattermost-server/pull/5#issuecomment-665705384)

 The auto assigner is not configured for this repository. Please talk with a Mattermost Github admin. thanks!

**Comment by agnivade** [comment]
In response to [this](https://github.com/mattermosttest/mattermost-server/pull/5#issuecomment-665705384)

 The auto assigner is not configured for this repository. Please talk with a Mattermost Github admin. thanks!

**Comment by agnivade** [comment]
Error trying to update the PR.
Please do it manually.

**Comment by agnivade** [comment]
Error trying to update the PR.
Please do it manually.

**Comment by isacikgoz** [comment]
test

**Comment by agnivade** [comment]
Trying to auto merge this PR.

**Comment by agnivade** [comment]
Pull Request successfully merged
SHA: a77204cbe1ba50f3c9cd28f83a0f20d4e694fdc2

**Pull request merged**
